channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - bokeh>=2.4.2,<3
  - cachey=0.2.1
  - cytoolz=0.12.0
  - dask=2023.7.1
  - distributed=2023.7.1
  - h5py
  - jq=1.6
  - jupyter-server-proxy
  - lz4>=4.3.2
  - msgpack-python
  - nomkl=3.0
  - numpy=1.23.5
  - pandas=1.5.1
  - python-blosc=1.10.6
  - scipy>=1.9.1
  - streamz=0.6.3
