channels:
  - defaults
  - conda-forge
dependencies:
  - cachey=0.2.1
  - cmake=3.22.1
  - cytoolz=0.12.0
  - dask=2022.11.0
  - distributed=2022.11.0
  - jq=1.6
  - jupyter-server-proxy
  - lz4=3.1.3
  - nomkl=3.0
  - numpy=1.23.1
  - pandas=1.5
  - pip
  - python-blosc=1.10.6
  - streamz=0.6.3
