channels:
  - defaults
  - conda-forge
dependencies:
  - cachey=0.2.1
  - cytoolz=0.12.0
  - dask=2022.11.1
  - jq=1.6
  - jupyter-server-proxy
  - lz4=4.0.2
  - msgpack-python=1.0.4
  - nomkl=3.0
  - numpy=1.23.5
  - pandas=1.5.1
  - pip
  - python-blosc=1.10.6
  - streamz=0.6.3
